### ISSUE TITLE
ZEVA - Create script to reset database for testing

### ISSUE THREAD

**Issue by emi-hi** [bcgov/zeva#1339]
**Describe the task**
Write a script that replaces test database with the zeva-test-for-restoring.tar file that is on teams (documets>general> zeva). Make sure that it can be run by any of the devs. Include documentation.

**Purpose**
The reason why this task is needed and/or what value it adds.

**Acceptance Criteria**
- [ ] Given I am a zelda developer
- [ ] when James or Al ask to have test reset
- [ ] I can easily run a script that resets the database

**Comment by emi-hi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1339?planning-poker) with Zenhub @AlexZorkin @JulianForeman @jig-patel @emi-hi @vibhiquartech @tim738745

**Comment by tim738745** [comment]
When I tried restoring “zeva-test-for-restoring.tar” I got the following error:
 
** Running pg_restore
pg_restore: while PROCESSING TOC:
pg_restore: from TOC entry 1; 3079 12980 EXTENSION plpgsql 
pg_restore: error: could not execute query: ERROR:  cannot drop extension plpgsql because other objects depend on it
DETAIL:  function user_management.create_application_user(text) depends on language plpgsql
function user_management.create_user(text) depends on language plpgsql
function user_management.create_role(text) depends on language plpgsql
function user_management.create_application_user_or_change_password(text,text) depends on language plpgsql
function user_management.revoke_admin(text) depends on language plpgsql
function user_management.drop_user(text) depends on language plpgsql
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
Command was: DROP EXTENSION plpgsql;
command terminated with exit code 1
 
So this means that there is a “user_management” schema in the database and that there are functions in there that depend on the plpgsql extension, which lives in the system schema. This “user_management” schema was created by a spilo script (https://github.com/zalando/spilo/blob/master/postgres-appliance/scripts/create_user_functions.sql); according to the github logs, we didn’t start using spilo until Jan 18, while the “zeva-test-for-restoring.tar” was dated Jan 13.
 
So my theory was that the dump contained no information on the “user_management” schema; that is, it did not know that it had to drop that schema and all objects inside it before dropping the plpgsql extension because it was created before that schema existed.
 
From https://www.postgresql.org/message-id/17322.1477919911%40sss.pgh.pa.us: “If you try a restore with -c into a database that has other random objects besides
what's in the dump, you could get errors from * dropping tables that are referenced by foreign
keys from tables not known in the dump * dropping functions that are used in views not
known in the dump * dropping operators or opclasses used by indexes
not known in the dump etc etc.”
 
Then, the solution, in my mind, was to drop the “user_management” schema (there’s no user data in there, just some functions created by spilo), and try to restore “zeva-test-for-restoring.tar” again).
 
Unfortunately, I got another error:
 
** Running pg_restore
pg_restore: while PROCESSING TOC:
pg_restore: from TOC entry 8; 2615 2200 SCHEMA public postgres
pg_restore: error: could not execute query: ERROR:  cannot drop schema public because other objects depend on it
DETAIL:  extension pg_stat_statements depends on schema public
function metric_helpers.pg_stat_statements(boolean) depends on type public.pg_stat_statements
view metric_helpers.pg_stat_statements depends on function metric_helpers.pg_stat_statements(boolean)
extension pg_stat_kcache depends on schema public
extension set_user depends on schema public
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
Command was: DROP SCHEMA public;
command terminated with exit code 1
 
So now it looks like there are a bunch of other objects that are dependent on the “public” schema that wasn’t there pre-spilo (e.g. by looking at the spilo github source code, the metric_helpers schema, and some of these extensions, were created by spilo scripts).
 
Instead of backing up these objects, then dropping them, then running the original restore, then putting those objects back, (kind of risky) maybe we can just set a new restore point right now? Take a new dump?
 
Note: I backed up the zeva test db before doing anything, and I restored it using the script below after I dropped the “user_management” schema; everything should be as it was.
 
The restore script:
 
#!/bin/bash
set -e
 
# This script takes a pg_dump .tar file from your local machine
# and automatically uploads and restores the .tar into 
# an openshift pod in the test environment
 
# Unlike copying from openshift to your local machine, you cannot copy single files when copying from your local machine to openshift
# But you can copy directories
# 3 Arguments
# $1 = path to directory (see argument 2)
# $2 = name of directory containing the .tar file you want to restore
# $3 = the name of the .tar file
# example command
# bash export-data.sh /Users/johndoe/Desktop zeva-dumps zeva.tar
 
if [ "$#" -ne 3 ]; then
    echo "Passed $# parameters. Expected 3."
    exit 1
fi
 
project_name='e52f12-test'
# the lead test db pod:
pod_name='zeva-spilo-0'
env='test'
 
local_path=$1
directory_name=$2
tar_file_name=$3
 
echo "** Checking Openshift creds"
oc whoami
echo "logged in"
echo
 
echo "** Setting project $env"
oc project $project_name
echo
 
echo "** Uploading the .tar file"
oc rsync $local_path/$directory_name $pod_name:/tmp
echo
 
echo "** Running pg_restore"
oc exec $pod_name -- bash -c 'pg_restore -U postgres -F t --no-privileges --no-owner --single-transaction -c -d zeva /tmp/'"$directory_name"'/'"$tar_file_name"''
echo
 
echo "** Cleaning up"
oc exec $pod_name rm -r /tmp/$directory_name
 
echo "** Finished database restore"

**Comment by tim738745** [comment]
In the end, I wrote a script that uploads sql scripts to zeva test on openshift, and executes it against the zeva database. We can use this script and the script Emily wrote (delete_all_supplementary.sql, on Teams: General -> Files -> Zeva) as input whenever we want to "reset" the test db.
