### ISSUE TITLE
ITVR - Investigate change in approved rebate levels

### ISSUE THREAD

**Issue by jdon-zev** [bcgov/zeva#1491]
**Problem Description** 
**The rebate program is running short of funds and want to potentially reduce the amount of rebate available to all levels of approved rebate applications.

**Solution Needs**
- The solution must communicate the changed rebate levels to the applicants and provide this new approved rebate level data to NCDA via the API.

**Timebox**
- See points on ticket

**Outcome**
Details describing the outcome of the research 
- Dev team to confirm the feasibility (or not) of making this change to approved rebate levels.
- Set out the steps required to make this change
- Detail any associated risks.

**Comment by tim738745** [comment]
[https://app.zenhub.com/files/223241604/4a7f232f-d173-49ad-9357-4b634467f6f3/download](https://app.zenhub.com/files/223241604/4a7f232f-d173-49ad-9357-4b634467f6f3/download)

Feasibility: Yes.

Steps required to make this change: Please see attached pdf at the top.

Risks/questions: When an application is "approved" on our end and "not-redeemed" on the NCDA's end, what exactly does that mean? I seem to recall the NCDA saying something about an applicant being "not-redeemed" even when they've bought a car (they have to keep the car for 6 months or something). I'm just a little bit concerned that we will be telling an applicant their rebate level changed when they've already bought a car...

Another question: Just to confirm, in the same release as the one containing the implementation of this proposed change, we are also changing the rebate amounts for all future applicants?

Notes:

(1) It would be prudent for the ncda to set up a test environment so that when testing this (whether locally or otherwise) we don’t have to use their prod environment; it doesn’t have to be anything fancy, just a new List (e.g. TestITVREligibilityList) that we can perform CRUD operations on via the API would be fine…

(2) We can update 100 approved applications per hour to the new rebate amounts (due to supposed NCDA API limitations); so for 5000 approved applications, that's a bit more than 2 days (48 hours).

**Comment by tim738745** [comment]
Another option: easiest thing to do would be to just continue doing things the way they are until the sum of all the max rebate amounts reach a certain number, and then just stop people from making applications from that point forth (or until there's more funds). We can build something so that analysts can see, in the console, the total value of all rebates approved/redeemed; alternatively, this total might be something they can grab directly from the database using CTHUB.

**Comment by tim738745** [comment]
@airinggov I'm not sure; perhaps the NCDA requires that we send them a number? But I think I see your point; if we refactored to store the levels A,B,C instead of the numbers, and this situation comes up again where we need to reduce the amounts of already approved rebates, then we wouldn't need to send updated data to the NCDA - we could just tell them that, for example, A now means 3500, B means 1500, etc.
