### ISSUE TITLE
ZEVA - Review of reassessment options for Toyota

### ISSUE THREAD

**Issue by jdon-zev** [bcgov/zeva#1656]
**Problem Description** 
**In order to** avoid reputational damage to the BC public service, the Clean Transportation team needs to be able to issue an accurate Assessment to Toyota for My2021 as soon as possible.

This requires completing a re-assessment of My2020 to correct their total LDV sales figure and the corresponding credit compliance reduction, then asking Toyota to re-submit their 2021 MY report so that is has the correct credit starting balance for making their 2021 Assessment.

Toyota's credits were adjusted using the administrative credit function and this appears as a transaction. This will also need to be removed as part of this work. 

**Solution Needs**
- Enter the non-negotiables of the solution (what are the needs vs. what are the wants)

**Timebox**
- Up to five points

**Outcome**
Details describing the outcome of the research 
- Was it successful? What direction should the work go? 
- Was it unsuccessful? Discuss next steps with team

**Additional Context**
- reassessments probably need to be completed and thoroughly tested before work is done on this card
- it seems like we will need to manually modify the credit transactions table in order to do this, so make sure to include in research the implications of that, what other tables need to be modified, etc
- once a solution is found, pull prod data locally and test solution. Show end results (the new model year report) to James and Al to check numbers etc

**Comment by AlexZorkin** [comment]
Steps to fix Toyota balance issue.
The issue is due to the incomplete reassessment report feature, which should allow them to correct the number of sales in the previous compliance period. In order to resolve this issue, we must complete the following steps:

**Complete reassessment feature with unit tests:** Implement the credits, deficits, and reductions components of the reassessment feature, and ensure they are functioning correctly with appropriate unit tests.

**Test with production data locally:** Pull production data onto a local machine and perform the following actions:

- Delete the 'Administrative Credit Reduction' record related to Toyota in the CreditTransaction table.
- Temporarily revert the balance to the incorrect value.
- Create a new reassessment with the correct LDV sales value.
- Submit and accept the reassessment on the government side.
- Confirm that Toyota's balance is adjusted correctly.

**Merge PRs to Test environment:** Merge the implemented features and bug fixes to the Test environment, and confirm that they are working correctly with test data.

**Deploy to Production:** Once the changes are approved in the Test environment, push them to production.

**Delete the 'Administrative Credit Reduction' record in Production:** Repeat the process from step 2 to delete the relevant record.

**Create a reassessment in Production:** Create a reassessment that addresses the LDV sales issue in the production environment.

**Toyota resubmits 2021 Model Year report:** Request Toyota to resubmit their 2021 Model Year report and verify that the updated value is being pulled through.

Please follow the above steps to fix the incorrect credit balance for the Toyota supplier in production.

**Comment by jdon-zev** [comment]
Alex to create a new card for the actions flowing out of this spike ticket.
