### ISSUE TITLE
ZEVA - MY Report Summary tab bugs

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1781]
**Describe the Bug**
For all BCeID and IDIR users:

1. MY Report summary tab is missing both service and records addresses. 
2. The ZEV Sales Submitted with this Report number is a whole number and should not have decimal places.

**Expected Behaviour**
The address information should be displayed and the sales number should not have decimal values.

**Actual Behaviour**
The address is not be displayed and the sales number has decimal places.

**Implications**
The missing address information is required by law, the summary screen is legal submission.
The decimal places are confusing and misleading.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role:
1. Go to a model year report
2. Click on summary tab
3. See errors as per screen capture

![myr-summary.PNG](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/b7e9e24a-d5b3-4779-8672-51bbe3d0d2f9)

Dev Notes: 
[ ] MY Report summary tab is missing both service and records addresses. 
1. As per James this isn't the issue in prod and occurring only in test.
2. Check if the code versions are different in prod and test or if the code restricts this only in test.
3. if it isn't above 2 cases then pass the data from backend and render them at the frontend. 

[ ] The ZEV Sales Submitted with this Report number is a whole number and should not have decimal places.
1. Check the data and restrict the field to only pass whole number.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1781?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton @tim738745

**Comment by JulianForeman** [comment]
After quickly checking Openshift, the test database had an entry on May 24th of this year that set both address fields to being empty.  This could have been intentional to test something? But it should be easily fixed through editing the organization on the application.  Alternatively I can create a new entry adding them back or delete the empty address so it defaults back 1.

I will check with Al, about this since his idir was the one that made the change and I don't want to undo a test scenario.

**Comment by airinggov** [comment]
Not sure what that would have been. It might have been to NOT show the Records Address label if there was no records address as it is optional.
