### ISSUE TITLE
ZEVA -ZEV Sales not appearing in Hyundai's MY report

### ISSUE THREAD

**Issue by shayjeff** [bcgov/zeva#2007]
**Describe the Bug**
Hyundai has pending and issued MY 2022 sales that are not showing up on the consumer ZEV sales page in 2022 MY report.  Similar situation to the Nissan issue that was resolved.

**Expected Behaviour**
These pending/issued sales should appear in the second tab of their MY report.

**Implications**
Hyundai will not see their MY2022 sales in their MY report.

**Steps To Reproduce**
Steps to reproduce the behaviour: The 2022 MY report has been submitted to the ZEVA system by the BCeID user.  Not sure if the MY report will have to be returned to the BCeID user to refresh the pages after the fix. 

**Development Checklist**
(1) Copy the production database onto your local machine and investigate why this is happening using the version of the app that is currently in production.
(2) Fix the issue.

**Comment by tim738745** [comment]
@shayjeff I took a look at this issue, and it looks like it's the same type of issue that happened with Nissan. There are a couple of options here:
(1) Send it back to Hyundai, after which I will make some data changes in the production database, then they should see their consumer sales, then they can resubmit.
or:
(2) I can make some code changes that address the underlying issue, then we can do a release to production. Note that this release will also contain everything that is "on dev", so this option will take longer because of testing, etc. Also, you will still have to send the report back to them for the sales to appear and for them to resubmit.

Let me know what you want to do!

**Comment by shayjeff** [comment]
@tim738745 option 1 works.  Should the report be returned today and approximately how long will the changes take before they can resubmit. The business would like to provide a timeline to Hyundai.  

Thanks Tim!

**Comment by tim738745** [comment]
@shayjeff Yes, you can return it today, then I can make the changes in a local copy of the database and confirm the numbers with you like last time (I'll send you a screenshot in teams), and then I can make the changes to the production database. This can probably all be done by the end of today; if not, then end of day Monday (I'm off tomorrow).

**Comment by shayjeff** [comment]
@tim738745 the report has been returned to Hyundai.

**Comment by tim738745** [comment]
@shayjeff okay, sounds good! I sent you a screenshot with the sales numbers on teams.

**Comment by tim738745** [comment]
The code fix for the underlying issue was also done as part of this card: https://github.com/bcgov/zeva/pull/2036
