### ISSUE TITLE
SPIKE: ZEVA - GMT Dates

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#2099]
**Problem Description** 
Dates are stored in ZEVA as GMT. This can cause issues if we don't adjust for PST date/time in the front end. Transactions can appear to be done in the wrong day. ZEVA requires deadlines to be met in PST.

**Solution Needs**
- Date/time needs to be displayed (and possibly recorded) throughout the system as PST regardless of the users local time zone.

**Timebox**
- One day of research

**Outcome**
Details describing the outcome of the research 
- Was it successful? What direction should the work go? 
- Was it unsuccessful? Discuss next steps with team

**Additional Context**
- See https://docs.djangoproject.com/en/5.0/topics/i18n/timezones/#overview for more information on how Django handles timestamps

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/2099?planning-poker) with Zenhub @JulianForeman @tim738745

**Comment by tim738745** [comment]
Echoing what Emily said above, plus a few notes:

From the Django Docs:
“When support for time zones is enabled, Django stores datetime information in UTC in the database, uses time-zone-aware datetime objects internally, and translates them to the end user’s time zone in templates and forms.
This is handy if your users live in more than one time zone and you want to display datetime information according to each user’s wall clock.
Even if your website is available in only one time zone, it’s still good practice to store data in UTC in your database. The main reason is Daylight Saving Time (DST). Many countries have a system of DST, where clocks are moved forward in spring and backward in autumn. If you’re working in local time, you’re likely to encounter errors twice a year, when the transitions happen. (The pytz documentation discusses these issues in greater detail.) This probably doesn’t matter for your blog, but it’s a problem if you over-bill or under-bill your customers by one hour, twice a year, every year. The solution to this problem is to use UTC in the code and use local time only when interacting with end users.”

According to this, it’s best practice to store dates in the UTC+00 (GMT) format, and to convert them to users’ timezones in the frontend, which is what we’re currently doing using moment.js.

However, if the ZEVA legislation or regulations state that dates need to be stored in PST or PDT, then we can make this change by setting USE_TZ to False, and setting TIME_ZONE to “America/Vancouver” (see https://docs.djangoproject.com/en/3.2/ref/settings/#std-setting-TIME_ZONE). To update previously saved timestamps, we can do a data migration (see https://docs.djangoproject.com/en/3.2/topics/migrations/#data-migrations). 

If there is relevant text contained in the legislation or regulations, please attach them to this card so developers can better assess what needs to be done, if anything.

**Comment by airinggov** [comment]
I think for ZEVA we don't care about the user's wall clock time, we probably want everything displayed as PST. This is especially true for the compliance report that must be submitted by 12:00 PM PST.
