### ISSUE TITLE
ZEVA - History Display on Older Model Year Reports

### ISSUE THREAD

**Issue by shayjeff** [bcgov/zeva#2106]
**Describe the Bug**
In the MYR history, inaccuracies arise where internal users are erroneously marked as report submitters, and duplicated entries suggest a MYR was returned by an analyst twice. This issue was identified and resolved with card #2066 for the 2022 MYR, however persist with older MYR. 

**Expected Behaviour**
The MYR history should accurately display the true actions completed.

**Actual Behaviour**
Despite addressing the bug for the current MY report (2022), older MYR history retains inaccuracies, misidentifying internal users as submitters and displaying duplicated analyst return entries.

**Implications**
These inaccuracies may lead to user confusion and compromise the accuracy of historical MYR data.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role:
1. As a government analyst, access the production environment.
2. Navigate to the assessment tab of various MYR records (Tesla 2021 and Toyota 2021.)
3. Observe instances where internal users are misidentified as submitters or where duplicated entries for MYR returns by an analyst are present.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/2106?planning-poker) with Zenhub @JulianForeman @tim738745

**Comment by tim738745** [comment]
Code changes were made that should fix the Tesla 2021 report history, but the Toyota 2021 report history accurately reflects the history data in the database. So it's the data that's incorrect, and we would have to go into the database to correct that. As for why the data is incorrect: I think it's because 
(1) requests are sent to the server asynchronously, and
(2) the analyst clicked the "Save" button and then immediately clicked the "Recommend" button (or the other way around)
We can address this issue by making it so that other buttons are disabled when a user clicks on "save" or "recommend" (this can be another card).
@shayjeff we can do the data change at the same time as the next release; please let me know if this works for you!

**Comment by shayjeff** [comment]
@tim738745, that works for me.
