### ISSUE TITLE
ZEVA - Snapshot Data in Model Year Report 

### ISSUE THREAD

**Issue by shayjeff** [bcgov/zeva#2156]
**Describe the task**
Ensure that all data is snapshotted during the assessment process. Once the assessment report is issued/assessed by the Director, the numbers should remain unchanged, and credit values should not be recalculated. 

**Purpose**
The purpose is make sure that there are no changes in credit values after the assessment report has been issued.
**Acceptance Criteria**
- [ ] Review the assessment process to determine which data points need to be snapshotted.
- [ ] Ensure that credit values are not recalculated once the assessment report is issued.

**Additional context**
It's uncertain whether this modification might affect the data transfer process for reassessments or supplementary reports. We need to make sure that the data is correctly pulled from the assessment to avoid any discrepancies.

**Development checklist**
(1) Compliance ratio reductions in the AssessmentContainer are currently calculated, and so the final balance is also calculated (the previous balance is snapshotted). So the reduction + final balance should be snapshotted and displayed.
(2) Use the snapshotted data in supplementary reports/reassessments.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/2156?planning-poker) with Zenhub @emi-hi @tim738745

**Comment by shayjeff** [comment]
@tim738745 - how do I test this?

**Comment by tim738745** [comment]
@shayjeff I think this card was mainly to make it so that even if there's code changes to the way compliance ratio reductions are calculated, the assessment page of assessed MYRs do not change. So, to test, we would have to make some temporary code changes and see that the data remains unchanged. I think the best way to do this would be for us to have a call, where I change some code on my locally running zeva app, and we confirm that the assessment numbers remain the same. Does that sound okay?

**Comment by shayjeff** [comment]
@tim738745 yes. that works for me.
