### ISSUE TITLE
ZEVA - Update Reporting Terminology from LDV Sales to Vehicles Supplied

### ISSUE THREAD

**Issue by shayjeff** [bcgov/zeva#2205]
**Describe the task**
Update the model year report in ZEVA to replace any instances of "Model Year LDV Sales:" or "Model Year LDV Sales/Leases:" with new terminology reflecting ‘supplied’ or ‘vehicles supplied’ numbers. This change aligns the reporting language with the updated regulatory requirements.

**Purpose**
The task is needed to comply with new regulatory requirements, which mandate that compliance obligations are based on wholesale vehicle supply rather than consumer sales.

**Acceptance Criteria**
- [ ] Update all instances of "Model Year LDV Sales:" or "Model Year LDV Sales/Leases:" in the model year report to reflect the new wholesale reporting terminology. which is **Vehicles supplied**
- [ ] Ensure the system accurately captures wholesale numbers for vehicles sold on or after October 1, 2024.

**Additional Context**
- The task is in response to changes in the ZEV Act and Regulation, which shift the focus from consumer sales to wholesale numbers for vehicles supplied into BC.
- The business area will provide the specific wording to use in ZEVA (this information still needs to be provided).

**Comment by ArawuSamuel1** [comment]
Got an email from tamara asking us to still maintain - the same wording that we have in the Act/Regulation which is would be ‘supplied’ or ‘vehicles supplied’ instead of using the term ‘wholesale’.

**Comment by ArawuSamuel1** [comment]
Shaylene also wanted me to let you know once we had decided what wording to include in the ZEVA system around ‘supplied or wholesaled’ for the changes starting October 1, 2024. I talked to my ED about this and we both agreed it would be best to use the same wording that we have in the Act/Regulation which is would be ‘supplied’ or ‘vehicles supplied’ instead of using the term ‘wholesale’. Happy to discuss this at all further if it would be helpful.
