### ISSUE TITLE
ZEVA - model weight flag

### ISSUE THREAD

**Issue by katerinkus** [bcgov/zeva#2331]
**Describe the task**
Model weight flag that appears if the weight is too high or is not entered, only gets displayed when you click away from the field. It should appear as you type in the weight.

**Purpose**
Avoid confusion for users.

**Acceptance Criteria**
- [ ] Red flag should appear when the user is still using the weight box.

**Comment by Lalita-Lala** [comment]
After testing this ticket and ZEVA overall, I have concluded that the described issue is not unique to this particular field. The behavior of displaying a notification or error this way is a standard behavior across all similar fields in the system.
Since this is not an isolated issue but rather a system-wide behavior, it doesn’t make sense to address it for just one field. Fixing it would require changes across the entire system. The best approach would be to include this behavior as part of the upcoming rebuild we are planning.
While this behavior might be slightly confusing for users or could slow them down, it does not prevent them from completing their actions. If a user enters a weight that exceeds the acceptable range, the system still displays the error before they can click “Save,” and the “Save” button remains disabled until the correct weight is entered in the field. As a result, the overall user flow is not affected.
This behavior should indeed be considered and incorporated as part of the changes in the upcoming rebuild to improve the user experience.

**Comment by shayjeff** [comment]
Closing card as we will incorporate this in the rebuild as suggested by the UX designer.
